version: 2.1

jobs:
 build:
   docker:
   # Primary container image where all steps run.
    - image: circleci/node:latest
   # Secondary container image on common network.
    - image: mcr.microsoft.com/mssql/server:2019-latest 
   steps:
     - checkout
     - run:
         name: Waiting for mssql to be ready
         command: |
           for i in `seq 1 10`;
           do
             nc -z localhost 1433 && echo Success && exit 0
             echo -n .
             sleep 1
           done
           echo Failed waiting for MSSQL && exit 1
     
