version: 2.1

orbs:
  win: circleci/windows@2.3.0

jobs:
 build:
   executor:
     name: win/default
     size: "large"
 #    shell: powershell.exe
   steps:
     - checkout
     - run: choco install dotnetcore --pre
     - run: choco install Microsoft.DotNet.Files --version 1.0.0-preview2-003121 --source https://dotnet.myget.org/F/dotnet-cli/api/v2
#     - run: choco install Microsoft.DotNet.Files --version 1.0.0-preview2-003121 --source https://dotnet.myget.org/F/dotnet-cli/api/v2
     - run: dotnet add package Microsoft.DotNet.Files --version 1.0.0-preview2-003121 --source https://dotnet.myget.org/F/dotnet-cli/api/v3/index.json 
     - run: dotnet tool install --global PowerShell
      #- run: pwsh -Command $Env:Path
     - run: pwsh -Command env
#     - run: pwsh -Command MSBuild C:\Users\circleci\project\dotnetapp-4.6.2\dotnetapp-4.6.2.sln
#     - run: MSBuild C:\Users\circleci\project\dotnetapp-4.6.2\dotnetapp-4.6.2.sln 
      #- run: pwsh ./build.ps1
     - run: dir "C:\Program Files (x86)\Microsoft Visual Studio\"
     - run: mkdir "c:\vs2017\"
     - run: systeminfo
     - run:
         name: "Check Docker"
         shell: powershell.exe
         command: |
           docker info
           docker run hello-world:nanoserver-1809
#     - run: choco install dotnetcore --pre 
#     - run: dotnet run 
#     - run: choco install MSTest.TestFramework --version 2.1.1 --source https://dotnet.myget.org/F/mstestv2/api/v2
#     - run: cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\TestAgent\Common7\IDE\"; .\MSTEST /testcontainer:C:\Users\circleci\project\hello-world-x86.dll 
     
