version: 2.1

orbs:
  win: circleci/windows@2.3.0

jobs:
 build:
   docker:
     - image: mcr.microsoft.com/dotnet/core/sdk:2.2
   steps:
     - checkout
 #    - run: systeminfo
     - run: docker build .
 #    - run:
 #        name: "Check Docker"
 #        shell: powershell.exe
 #        command: |
 #          docker info
 #          docker build .
 #    - run: choco install visualstudio2019testagent
 #    - run: choco install MSTest.TestFramework --version 2.1.1 --source https://dotnet.myget.org/F/mstestv2/api/v2
 #    - run: cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\TestAgent\Common7\IDE\"; .\MSTEST /testcontainer:C:\Users\circleci\project\hello-world-x86.dll 
     
