version: 2.1

orbs:
  win: circleci/windows@2.3.0

jobs:
 build:
   executor:
     name: win/default
     size: "large"
 #    shell: powershell.exe
   steps:
     - checkout
#     - run: dotnet tool install --global PowerShell
#     - run: pwsh ./RemoveCoreSDKs.ps1
     - run: choco install dotnetcore --pre
#     - run: choco install dotnet-core-uninstall 
#     - run: dotnet-core-uninstall remove --sdk --all-below 3.1.102 --force
#     - run: dotnet add package Microsoft.DotNet.Files --version 1.0.0-preview2-003121 --source https://dotnet.myget.org/F/dotnet-cli/api/v3/index.json 
#     - run: dotnet tool install --global PowerShell
     - run: dotnet run 
     
