version: 2.1

orbs:
  win: circleci/windows@2.3.0

jobs:
 build:
   executor:
     name: win/default
     size: "large"
 #    shell: powershell.exe
   steps:
     - checkout
     - run: docker build -t my-dotnet46-app .
