version: 2.1

#orbs:
#  win: circleci/windows@2.3.0

jobs:
 build:
   docker:
     - image: jetcipher/circleci-dotnet-core:3.0
   steps:
     - checkout
     - setup_remote_docker:
         docker_layer_caching: true
 #    - run: systeminfo
 #    - run: apt-get update
 #    - run: apt install sudo
 #    - run: sudo apt install docker.io
 #    - run: sudo systemctl start docker
 #    - run: sudo systemctl enable docker
     - run: docker --version
     - run: docker build .
 #    - run:
 #        name: "Check Docker"
 #        shell: powershell.exe
 #        command: |
 #          docker info
 #          docker build .
 #    - run: choco install visualstudio2019testagent
 #    - run: choco install MSTest.TestFramework --version 2.1.1 --source https://dotnet.myget.org/F/mstestv2/api/v2
 #    - run: cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\TestAgent\Common7\IDE\"; .\MSTEST /testcontainer:C:\Users\circleci\project\hello-world-x86.dll 
     
