version: 2.1

orbs:
  win: circleci/windows@1.0.0

jobs:
 build:
   executor:
     name: win/vs2019
     size: "large"
     shell: powershell.exe
   steps:
     - checkout
     - run: docker build -t my-dotnet46-app .
